Cu 86c11rv16 automated tests
jembi/climate-mediator pull request #8
Opened 2024-11-21 12:53 UTC by brett-onions

- allows for the listening to multiple buckets
- updated GitHub action to use docker compose file for testing
- merging with s3 data insertion

2024-11-22 08:03 UTC, sushantpatil1214 commented on src/utils/minio.ts
> +import * as Minio from 'minio';
@brett-onions Update the latest change from the minioClient file.

2024-11-22 08:19 UTC, drizzentic commented on src/index.ts
> +const prefix = getConfig().runningMode === 'testing' ? '/' : '/climate';
We can maintain `/` as default since the platform channel registration forwards to `/upload`.

2024-11-22 08:19 UTC, drizzentic commented on src/utils/minio.ts
> +
```suggestion
import crypto from 'crypto';
```

2024-11-22 08:19 UTC, drizzentic commented on src/config/config.ts
> +    createSampleTable: process.env.CREATE_SAMPLE_TABLE === 'true' ? true : false,
what is the role of this property?

2024-11-22 09:06 UTC, marvinIsSacul requested changes
Looks good. Just a couple of suggestions.

2024-11-22 09:06 UTC, marvinIsSacul commented on src/utils/minio.ts
> +          const fileBuffer = await readFile(`tmp/${file}`);
How big of a file are we expecting on average? And what's the biggest file we are expecting? We might need to read the files as a stream? @drizzentic

2024-11-22 09:06 UTC, marvinIsSacul commented on src/utils/minio.ts
> +      minioClient.fGetObject(bucket, file, `tmp/${file}`, async (err) => {
This entire listener needs to handle any exceptions since it's `async` and `await`?

2024-11-22 09:06 UTC, marvinIsSacul commented on tests/services/table-creation.test.ts
> +    const csvFile = Buffer.from('id,name,age\n1,John,20\n2,Jane,21');
See if it handles Windows style new line chars as well.

2024-11-22 09:06 UTC, marvinIsSacul commented on src/utils/minio.ts
> +  // Check if bucket exists, create if it doesn't
Probably need to add more logging here. Indicating that you're uploading file to Minio...

2024-11-22 09:30 UTC, brett-onions commented on src/config/config.ts
> +    createSampleTable: process.env.CREATE_SAMPLE_TABLE === 'true' ? true : false,
This was a for the purchased data, since we are not adding it to this repo I will remove this property

2024-11-22 10:45 UTC, drizzentic commented on src/utils/minio.ts
> +          const fileBuffer = await readFile(`tmp/${file}`);
At the moment we really don't have a hard limit in terms of the file size. Depending on the mediator purpose we will always customize this. At the moment we are working with a 63mb file. @marvinIsSacul

2024-11-22 11:54 UTC, brett-onions commented on tests/services/table-creation.test.ts
> +    const csvFile = Buffer.from('id,name,age\n1,John,20\n2,Jane,21');
nice one, I have implemented the test

2024-11-22 13:31 UTC, marvinIsSacul requested changes
Looks good. Just one suggestion.

2024-11-22 13:31 UTC, marvinIsSacul commented on src/utils/minioClient.ts
> +        minioClient.fGetObject(bucket, file, `tmp/${file}`, async (err) => {
see if you can use Promises consistently. Instead of using this callback intertwined with other promises.

2024-11-25 10:51 UTC, marvinIsSacul approved these changes

2024-11-25 10:51 UTC, merged